name: validate
on:
  push:
    branches:
      # Match SemVer major release branches
      # e.g. "12.x" or "8.x"
      - '[0-9]+.x'
      - 'main'
      - 'next'
      - 'next-major'
      - 'beta'
      - 'alpha'
      - '!all-contributors/**'
  pull_request: {}
jobs:
  main:
    # ignore all-contributors PRs
    if: ${{ !contains(github.head_ref, 'all-contributors') }}
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
        with:
          # required by codecov/codecov-action
          fetch-depth: 0

      - name: ⎔ Setup node
        uses: actions/setup-node@v3

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: Verify format (`npm run format` committed?)
        run: npm run format -- --check --no-write

      - name: ▶️ Run validate script
        run: npm run validate

      - name: ⬆️ Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
